spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to Aljis accounts related local APIs "
  contactDetails:
    name: "Abdul Musavveer Alji - Developer"
    email: "techie.alji@aljis.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345