build:
  version: "1.0"

accounts:
  message: "Welcome to Alijs accounts related prod APIs "
  contactDetails:
    name: "Abdul Musavveer Alji Sr - Product Owner"
    email: "techie.alji@aljis.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384